apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-example
  namespace: production
  labels:
    project: k8s-security-lab
    security-control: secrets-management
type: Opaque
data:
  username: ZXhhbXBsZS11c2VybmFtZQ==
  password: RVhBTVBMRS1QQVNTV09SRA==
